### PR TITLE
[Windows] Fix issue with Laravel Herd

### LINKED ISSUE #61: LaravelPint does not work with the Windows version of laravelHerd
**Describe the bug**
When command is executed from terminal, it is formatted properly. But when the file is saved, it is not formatted.

### PR DESCRIPTION
**Pull request by vikas5914**
Fix #61

### CODE REVIEW

**Review by d8vjork — COMMENTED** [review]
Is this particularly to a OS? As plenty of other users had an issue with other OS like Mac OS or Linux I'm curious if this will solve all the problems

**Comment by d8vjork** [comment]
Also please do check this with WSL so we don't break stuff that was working before (I believe many will not attempt to change all their working environment to Laravel Herd) :)

**Comment by vikas5914** [comment]
@d8vjork I checked the code, and it does not run the sail command.  

The format file function does not use sail.  Am I missing something?

https://github.com/open-southeners/vscode-laravel-pint/blob/55c36031eef1930beb87e566a85bd0f3a1684fde/src/PintEditService.ts#L191-L193.

**Comment by d8vjork** [comment]
@vikas5914 That's in the workspace formatting, the save has the pint within sail resolver

**Comment by vikas5914** [comment]
> @vikas5914 That's in the workspace formatting, the save has the pint within sail resolver
> 
> https://github.com/open-southeners/vscode-laravel-pint/blob/55c36031eef1930beb87e566a85bd0f3a1684fde/src%2FPintEditService.ts#L125-L127

I checked the code again, but the function `handleActiveTextEditorChanged` (line # 101-152) does not execute the `run()` command. 

Also, I put the console log in the `run()` command, and it's not using the sail command at all.

**Comment by d8vjork** [comment]
@vikas5914 are you trying to save a changed .php file? Also did you configure the extension so it formats on save (or manually triggering this format)

**Comment by vikas5914** [comment]
@d8vjork d8vjork yes.. I am trying to save a changed.PHP file, and I have set its format to save. This is my settings 

```
{
  "[php]": {
      "editor.insertSpaces": false,
      "editor.formatOnSave": true,
      "editor.defaultFormatter": "open-southeners.laravel-pint"
    },
  
 "laravel-pint.enableDebugLogs": true,
  "laravel-pint.preset": "laravel",
 "laravel-pint.fallbackToGlobalBin": false,
  "laravel-pint.enable": true,
  "laravel-pint.runInLaravelSail": true
}

**Comment by vikas5914** [comment]
@d8vjork, any comment on the above info?

**Comment by vikas5914** [comment]
@d8vjork hey.,. any update on this PR?

**Pull request merged**
